name: Deployment

on:
  push:
    branches: [build_CICD_pipeline]

jobs:
  build_and_test:
    name: DDK ki pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Github Action Setup
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies with poetry
        run: |
          poetry install --only main

      - name: Test Run
        run: |
          poetry run python FunctionTest.py

      - name: Build
        run: |
          poetry build
